=== treiche/db_agg/etc/database-registry.dtd
<!ELEMENT registry (system*,database-definition*)>
<!ATTLIST registry databaseNamingStrategy CDATA #IMPLIED>

<!ELEMENT system (host*)>
<!ATTLIST system name CDATA #IMPLIED>

<!ELEMENT host (server*)>
<!ATTLIST host name CDATA #IMPLIED>

<!ELEMENT server (database-instance*)>
<!ATTLIST server
          port    CDATA   #IMPLIED
          type    CDATA   #IMPLIED>

<!ELEMENT database-instance EMPTY>
<!ATTLIST database-instance
          id      IDREF  #REQUIRED
          name    CDATA   #IMPLIED
          shard   CDATA   #IMPLIED
          worker  CDATA   #IMPLIED>

<!ELEMENT database-definition (sharding-strategy*,namespace*)>
<!ATTLIST database-definition
          name      ID     #REQUIRED>

<!ELEMENT sharding-strategy EMPTY>
<!ATTLIST sharding-strategy
          name      CDATA  #REQUIRED
          shardCol  CDATA  #REQUIRED>

<!ELEMENT namespace EMPTY>
<!ATTLIST namespace
          name    CDATA   #REQUIRED>

=== treiche/db_agg/tests/data/database-registry.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE registry PUBLIC "database-registry.dtd" "../../etc/database-registry.dtd">
<registry databaseNamingStrategy="{{system}}_{{id}}{{shardId}}_db">
    <system name="local">
        <host name="localhost">
            <server port="11213" type="memcached"/>
            <server port="5432">
                <database-instance id="sharded" shard="1"/>
                <database-instance id="sharded" shard="2"/>
                <database-instance id="sharded" shard="3"/>
                <database-instance id="sharded" shard="4"/>
                <database-instance id="sharded" shard="5"/>
                <database-instance id="sharded" shard="6"/>
                <database-instance id="sharded" shard="7"/>
                <database-instance id="sharded" shard="8"/>
                <database-instance id="unsharded" name="local_unsharded_db" worker="true"/>
            </server>
            <server port="5435">
                <database-instance id="shardedtwo" shard="1"/>
                <database-instance id="shardedtwo" shard="2"/>
                <database-instance id="shardedtwo" shard="3"/>
                <!--
                <database-instance id="shardedtwo" shard="4"/>
                <database-instance id="shardedtwo" shard="5"/>
                <database-instance id="shardedtwo" shard="6"/>
                <database-instance id="shardedtwo" shard="7"/>
                <database-instance id="shardedtwo" shard="8"/>
                -->
            </server>
<!--
	    <server port="5435">
                <database-instance id="bm" name="local_bm_db" worker="true"/>
	    </server>
-->
        </host>
    </system>
    <system name="prod">
        <host name="localhost">
            <server port="5432">
                <database-instance id="sharded" shard="1"/>
                <database-instance id="sharded" shard="2"/>
                <database-instance id="sharded" shard="3"/>
                <database-instance id="sharded" shard="4"/>
                <database-instance id="sharded" shard="5"/>
                <database-instance id="sharded" shard="6"/>
                <database-instance id="sharded" shard="7"/>
                <database-instance id="sharded" shard="8"/>
                <database-instance id="unsharded"/>
            </server>
        </host>
    </system>
    <database-definition name="sharded">
        <sharding-strategy name="md5" shardCol=".*code.*"/>
        <sharding-strategy name="explicit" shardCol=".*shard_id.*"/>
        <namespace name="ns1"/>
    </database-definition>
    <database-definition name="unsharded">
        <namespace name="ns2"/>
    </database-definition>
    <database-definition name="shardedtwo">
        <sharding-strategy name="modulo" shardCol=".*user_id.*"/>
        <sharding-strategy name="explicit" shardCol=".*shard_id.*"/>
        <namespace name="ns3"/>
    </database-definition>
</registry>
