=== treiche/db_agg/etc/url-registry.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="urls" type="UrlType">
        <xsd:key name="ID">
            <xsd:selector xpath="book|author|character"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
	  <xsd:keyref name="IDREF" refer="ID">
	    <xsd:selector xpath="book/author-ref|book/character-ref"/>
	    <xsd:field xpath="@ref"/>
	  </xsd:keyref>
    </xsd:element>


    <xsd:complexType name="UrlType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
           <xsd:element name="environment" type="EnvironmentType" maxOccurs="unbounded"/>
           <xsd:element name="globals" type="GlobalsType" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="EnvironmentType">
	    <xsd:sequence minOccurs="1" maxOccurs="unbounded">
	       <xsd:element name="protocol" type="ProtocolType"/>
	    </xsd:sequence>
	    <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="ProtocolType">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
           <xsd:element name="host" type="HostType"/>
           <xsd:element name="path" type="PathType"/>
        </xsd:choice>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="HostType">
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">
           <xsd:element name="port" type="PortType"/>
        </xsd:sequence>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="PortType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
           <xsd:element name="path" type="PathType"/>
        </xsd:sequence>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="PathType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
           <xsd:element name="match" type="MatchType"/>
           <xsd:element name="path" type="PathType"/>
           <xsd:element name="parameter" type="ParameterType"/>
           <xsd:element name="sharding-strategy" type="ShardingStrategyType"/>
        </xsd:choice>
        <xsd:attribute name="worker" type="xsd:boolean"/>
        <xsd:attribute name="type" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
        <xsd:attribute name="ref" type="xsd:IDREF"/>
        <xsd:attribute name="id" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:complexType name="ParameterType">
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="GlobalsType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
           <xsd:element name="path" type="PathType"/>
           <xsd:element name="parameter" type="ParameterType"/>
           <xsd:element name="protocol" type="ProtocolType"/>
           <xsd:element name="host" type="HostType"/>
           <xsd:element name="port" type="PortType"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="MatchType">
        <xsd:attribute name="regexp" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="ShardingStrategyType">
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="shardCol" type="xsd:string"/>
    </xsd:complexType>
</xsd:schema>

=== treiche/db_agg/tests/data/url-registry.xml
<urls
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../etc/url-registry.xsd"
>
    <environment name="local">
        <protocol value="file">
            <path value="/home/arnd/tmp/db_agg_installed/tests/data">
                <path ref="unsharded" value="local_unsharded_db.sqlite3">
                    <match regexp="(from|join)\s+article"/>
                </path>
                <path ref="sharded" value="local_sharded1_db.sqlite3">
                    <match regexp="(from|join)\s+price"/>
                </path>
                <path ref="sharded" value="local_sharded2_db.sqlite3">
                    <match regexp="(from|join)\s+price"/>
                </path>
                <path ref="sharded" value="local_sharded3_db.sqlite3">
                    <match regexp="(from|join)\s+price"/>
                </path>
                <path ref="sharded" value="local_sharded4_db.sqlite3">
                    <match regexp="(from|join)\s+price"/>
                </path>
            </path>
        </protocol>
    </environment>
    <globals>
        <path id="sharded">
            <sharding-strategy name="md5" shardCol=".*code.*"/>
        </path>
        <path id="unsharded"/>
    </globals>
 </urls>
