=== treiche/db_agg/etc/xml-query.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="queries" type="QueriesType">
    </xsd:element>

    <xsd:complexType name="QueriesType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
           <xsd:element name="execution" type="ExecutionType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ExecutionType">
        <xsd:sequence minOccurs="1" maxOccurs="1">
           <xsd:element name="query" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:Name" use="required"/>
        <xsd:attribute name="shardId" type="xsd:string"/>
        <xsd:attribute name="type" type="xsd:Name"/>
    </xsd:complexType>

</xsd:schema>

=== treiche/db_agg/tests/queries/locator.xml
<queries
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../etc/xml-query.xsd">

    <execution name="one_shard" type="sqlite3" shardId="3">
        <query>
            select article_code, price
              from price
        </query>
    </execution>

    <execution name="all_shards" type="sqlite3">
        <query>
            select price, article_code
              from price
        </query>
    </execution>


    <execution name="join_one_shard" type="sqlite3">
        <query>
            select article_code, price
              from one_shard
              join article
                on code = article_code
        </query>
    </execution>

    <execution name="select_one_shard" type="sqlite3">
        <query>
            select article_code, price
              from all_shards$4
              join article
                on code = article_code
        </query>
    </execution>


</queries>
